<?
$PERM["registration"]["G2"]="R";
$PERM["registration"]["G6"]="R";
$PERM["registration"]["G12"]="R";
$PERM["registration"]["G11"]="R";
$PERM["registration"]["G16"]="R";
$PERM["registration"]["G14"]="R";
$PERM["registration"]["G17"]="R";
$PERM["registration"]["G21"]="R";
$PERM["registration"]["G20"]="R";
$PERM["registration"]["G7"]="R";
$PERM["registration"]["G8"]="R";
$PERM["registration"]["G9"]="R";
$PERM["registration"]["G10"]="R";
$PERM["registration"]["G19"]="R";
$PERM["registration"]["G18"]="R";
$PERM["registration"]["*"]="R";
?>