<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Продукты");
$APPLICATION->SetPageProperty("SHOW_BANNERS","Y");
?>
<?$APPLICATION->IncludeComponent("areal:catalog", "template1", array(
	"IBLOCK_TYPE" => "catalog",
	"IBLOCK_ID" => "4",
	"BASKET_URL" => "/personal/basket.php",
	"ACTION_VARIABLE" => "action",
	"PRODUCT_ID_VARIABLE" => "id",
	"SECTION_ID_VARIABLE" => "SECTION_ID",
	"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"PRODUCT_PROPS_VARIABLE" => "prop",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/catalog/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "N",
	"CACHE_GROUPS" => "Y",
	"SET_TITLE" => "Y",
	"SET_STATUS_404" => "Y",
	"USE_ELEMENT_COUNTER" => "Y",
	"USE_FILTER" => "Y",
	"FILTER_NAME" => "arrFilter1",
	"FILTER_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_PROPERTY_CODE" => array(
		0 => "",
		1 => "other_product",
		2 => "",
	),
	"FILTER_PRICE_CODE" => array(
	),
	"USE_REVIEW" => "N",
	"USE_COMPARE" => "Y",
	"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
	"COMPARE_FIELD_CODE" => array(
		0 => "NAME",
		1 => "PREVIEW_PICTURE",
		2 => "",
	),
	"COMPARE_PROPERTY_CODE" => array(
		0 => "",
		1 => "KKMPrinter",
		2 => "ZBRPL",
		3 => "ZBRSS",
		4 => "ZBRTT",
		5 => "ZBRPT",
		6 => "hldrhrngl",
		7 => "batterychar",
		8 => "ZBRBC",
		9 => "emulation",
		10 => "type_yasch",
		11 => "tip_zamka",
		12 => "type_knop",
		13 => "schityvatel_mafn_kart",
		14 => "kolvo_kupyur",
		15 => "kolvo_monet",
		16 => "type_scan",
		17 => "type_scan_module",
		18 => "bar_codes_1d",
		19 => "bar_codes_2d",
		20 => "istochnik_sveta",
		21 => "skorost_scan",
		22 => "kolvo_scan_lin",
		23 => "ploskost_scan",
		24 => "rasstoyan_schit",
		25 => "shirina_schit",
		26 => "min_sh_shk",
		27 => "kontr_koda",
		28 => "osvesh_scan",
		29 => "category_products",
		30 => "tehnolog_zasch",
		31 => "max_weight",
		32 => "min_weight",
		33 => "oblast_prim",
		34 => "accuracy_class",
		35 => "scale_e_d",
		36 => "max_tare",
		37 => "max_plu",
		38 => "memory",
		39 => "ozu_memory",
		40 => "displays",
		41 => "op_disp_type",
		42 => "POSMBName",
		43 => "POSMBSize",
		44 => "POSCPUName",
		45 => "POSCPUClockSpeed",
		46 => "miniPOSCPUClockSpeed",
		47 => "POSCPUCache",
		48 => "POSChipSet",
		49 => "POSRAMStandardSize",
		50 => "miniPOSRAMSize",
		51 => "miniPOSFlashRAM",
		52 => "POSRAMType",
		53 => "POSRAMSlotsQty",
		54 => "POSRAMMaxSize",
		55 => "op_disp_dim",
		56 => "POSHDDSize",
		57 => "POSSSDSize",
		58 => "POSInterfaces",
		59 => "POSCashierDisplay",
		60 => "POSCashierDisplayType",
		61 => "POSCashierDisplaySizeAndResolution",
		62 => "POSCashierDisplayBrightness",
		63 => "POSKeyboard",
		64 => "POSKeyboardModel",
		65 => "POSKeyboardInterface",
		66 => "cust_disp_type",
		67 => "POSKeyboardKeysQty",
		68 => "miniPOSHotKeyQty",
		69 => "POSKeyboardLock",
		70 => "POSMSR",
		71 => "POSMSRTracks",
		72 => "POSCustomerDisplay",
		73 => "POSCustomerDisplayModel",
		74 => "POSCustomerDisplayType",
		75 => "POSCustomerDisplaySpecs",
		76 => "POSOptionalExternalCustomerDisplay",
		77 => "cust_disp_dim",
		78 => "POSCurrencyDetector",
		79 => "POSSecurity",
		80 => "POSPrinter",
		81 => "POSPrinterModel",
		82 => "POSCashDrawer",
		83 => "POSCashDrawerModel",
		84 => "POSCashDrawerDimensions",
		85 => "POSCashDrawerBillTrays",
		86 => "POSCashDrawerCoinTrays",
		87 => "POSCashDrawerSlipSlot",
		88 => "POSOperatingSystem",
		89 => "POSFrontSoft",
		90 => "miniPOSOptions",
		91 => "keyboard_type",
		92 => "keys",
		93 => "resurs_najatiy",
		94 => "kolvo_pol_klyuch",
		95 => "plu_keys",
		96 => "print_type",
		97 => "printing_resolution",
		98 => "print_type_nos",
		99 => "print_width",
		100 => "paper_width",
		101 => "paper_width_min",
		102 => "printing_length_max",
		103 => "printing_length_min",
		104 => "max_paper_diameter",
		105 => "core_id_min",
		106 => "core_id_max",
		107 => "tph_life",
		108 => "prn_speed",
		109 => "SD_card",
		110 => "interfeis",
		111 => "character_set",
		112 => "datchiki",
		113 => "skorost_proezda",
		114 => "power_type",
		115 => "power_ext",
		116 => "input",
		117 => "output",
		118 => "temperature_range_operation",
		119 => "temperature_range_storage",
		120 => "min_temp",
		121 => "max_temp",
		122 => "Humidity",
		123 => "zaschischennost",
		124 => "platform_dim",
		125 => "equipment_dim",
		126 => "package_dim",
		127 => "equipment_netto",
		128 => "ProductWeight",
		129 => "equipment_brutto",
		130 => "udaroproch",
		131 => "vlagozaschischennost",
		132 => "pylezasch",
		133 => "CaseMaterial",
		134 => "color_of_korpus",
		135 => "platform_formfactor",
		136 => "drivers",
		137 => "POSCashierDisplaySize",
		138 => "POSCashierDisplayResolution",
		139 => "POSCashierDisplayTouch",
		140 => "res_pech_gol",
		141 => "temperature_range",
		142 => "vlajnost",
		143 => "",
	),
	"COMPARE_ELEMENT_SORT_FIELD" => "sort",
	"COMPARE_ELEMENT_SORT_ORDER" => "asc",
	"DISPLAY_ELEMENT_SELECT_BOX" => "N",
	"PRICE_CODE" => array(
	),
	"USE_PRICE_COUNT" => "N",
	"SHOW_PRICE_COUNT" => "1",
	"PRICE_VAT_INCLUDE" => "Y",
	"PRICE_VAT_SHOW_VALUE" => "N",
	"PRODUCT_PROPERTIES" => array(
	),
	"USE_PRODUCT_QUANTITY" => "N",
	"CONVERT_CURRENCY" => "N",
	"SHOW_TOP_ELEMENTS" => "Y",
	"TOP_ELEMENT_COUNT" => "1",
	"TOP_LINE_ELEMENT_COUNT" => "1",
	"TOP_ELEMENT_SORT_FIELD" => "sort",
	"TOP_ELEMENT_SORT_ORDER" => "asc",
	"TOP_PROPERTY_CODE" => array(
		0 => "",
		1 => "",
	),
	"SECTION_COUNT_ELEMENTS" => "Y",
	"SECTION_TOP_DEPTH" => "10",
	"PAGE_ELEMENT_COUNT" => "10",
	"LINE_ELEMENT_COUNT" => "1",
	"ELEMENT_SORT_FIELD" => "sort",
	"ELEMENT_SORT_ORDER" => "asc",
	"LIST_PROPERTY_CODE" => array(
		0 => "",
		1 => "device_type",
		2 => "max_weight",
		3 => "",
	),
	"INCLUDE_SUBSECTIONS" => "Y",
	"LIST_META_KEYWORDS" => "-",
	"LIST_META_DESCRIPTION" => "-",
	"LIST_BROWSER_TITLE" => "-",
	"DETAIL_PROPERTY_CODE" => array(
		0 => "",
		1 => "",
		2 => "",
	),
	"DETAIL_META_KEYWORDS" => "keywords",
	"DETAIL_META_DESCRIPTION" => "description",
	"DETAIL_BROWSER_TITLE" => "seo_title",
	"LINK_IBLOCK_TYPE" => "",
	"LINK_IBLOCK_ID" => "",
	"LINK_PROPERTY_SID" => "",
	"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
	"USE_ALSO_BUY" => "N",
	"USE_STORE" => "N",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "Y",
	"PAGER_TITLE" => "Товары",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_TEMPLATE" => "",
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	"PAGER_SHOW_ALL" => "Y",
	"AJAX_OPTION_ADDITIONAL" => "",
	"SEF_URL_TEMPLATES" => array(
		"sections" => "",
		"section" => "#SECTION_CODE#/",
		"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
		"compare" => "compare.php",
	)
	),
	false
);?>
<?
if(CModule::IncludeModule("iblock"))
{
	CityDefinition();
	$arResult = GetLocationInformation();
	if(!empty($arResult["REGIONS"])):?>
<script>
$(document).ready(function(){
	$('input[name=form_text_172]').search_place_input('change',{name: '<?=($arResult["REGIONS"][$arResult["SELECTED_COUNTRY"]][$arResult["SELECTED_REGION"]])?$arResult["REGIONS"][$arResult["SELECTED_COUNTRY"]][$arResult["SELECTED_REGION"]]:''?>',});
 	$('input[name=form_text_171]').search_place_input('change',{name: '<?=($arResult["TOWNS"][$arResult["SELECTED_REGION"]][$arResult["SELECTED_TOWN"]])?$arResult["TOWNS"][$arResult["SELECTED_REGION"]][$arResult["SELECTED_TOWN"]]:''?>',});
});
</script>
	<?endif;?>
<?}?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>